### ISSUE TITLE
Camelize is not defined error

### ISSUE THREAD

**Issue by Waylonf** [oriongunning/gridder-js#4]
I am getting an error which seems to be calling an undefined function or method with the name camelize

**Comment by kmeronuk** [comment]
Same issue here:
`Uncaught ReferenceError: camelize is not defined
    at l.optionsForElement (gridder-js-min.js:1:6790)
    at new l (gridder-js-min.js:1:1286)`

Removing camelize() makes things work so far

**Comment by saad-edgedesign** [comment]
@kmeronuk Removing the "camelize()" function surely works but in my case, I used ID to catch my element rather than Class Name and that also worked because in my opinion changing something in the library is not a good idea.

**Comment by Waylonf** [comment]
I agree, unfortunatley it seems this repo is no longer maintained, very
unfortunate.

**Comment by orion3dgames** [comment]
I've removed that camelize function, no idea why it was there anyway. To be honest, I did not think many people were using it :)

**Comment by Waylonf** [comment]
Awesome, the fact that this is not used by the masses is one of the best things about gridder-js, many thanks :-)

**Comment by saad-edgedesign** [comment]
@oriongunning Thanks very much for the fix, I still use it in most of my projects.
