### ISSUE TITLE
Unpkg library doesn't have the responsive version

### ISSUE THREAD

**Issue by lornehub** [oriongunning/gridder-js#5]
Hey there,

Is it possible to update the unpkg library?   I'm trying to add breakpoints but the version they provide doesn't appear to have those as options.

**Comment by orion3dgames** [comment]
Hi there, that's correct, I forgot to publish to NPM. You should now be able to use this link: https://unpkg.com/gridder-js@0.7.0/dist/gridder-js.js

**Comment by lornehub** [comment]
Dude, so fast! Thank you so much! You rock :)

**Comment by lornehub** [comment]
Sorry, back so fast.  It's throwing a couple of errors 
1) Require is not defined...think it's related to this:
var $f7gn8$justextend = require("just-extend");

**Comment by orion3dgames** [comment]
Ok, you need the standalone version, try this one instead: https://unpkg.com/gridder-js@0.7.0/dist/gridder-js-min.js

**Comment by lornehub** [comment]
That's the one! Thank you so much!

**Comment by orion3dgames** [comment]
Cool, I'll close this now :)
